project:
  output-dir: "_staff-site"

# Modify aesthetics and add docs to navbar
website:
  title: "Stat 20 Staff Site"
  draft-mode: visible
  open-graph:
    site-name: "Stat 20 Staff Site"
  navbar:
    background: warning
    right:
      - text: "Docs"
        href: docs/index.qmd
  sidebar:
    - id: Docs
      title: "Docs"
      style: docked
      align: left
      contents:
        - section: Documention
          href: docs/index.qmd
          contents:
            - docs/website.qmd
            - docs/assignments.qmd
            - docs/slides.qmd
        